<?php
declare(strict_types=1);
const STUDIO_SESSION_TTL = 28800;
function studioConfig(string $key): string { return trim((string)(getenv($key) ?: ($_ENV[$key] ?? ''))); }
function studioStartSession(): void { if(session_status()===PHP_SESSION_ACTIVE)return; session_name('vibe_studio'); session_start(['use_strict_mode'=>true,'cookie_httponly'=>true,'cookie_samesite'=>'Strict','cookie_secure'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'),'cookie_lifetime'=>STUDIO_SESSION_TTL,'gc_maxlifetime'=>STUDIO_SESSION_TTL]); }
function studioCsrf(): string { studioStartSession(); return $_SESSION['studio_csrf']??=bin2hex(random_bytes(32)); }
function studioSession(): string { return studioCsrf(); }
function studioAuthenticated(): bool { studioStartSession(); $at=(int)($_SESSION['studio_authenticated_at']??0); $sig=(string)($_SESSION['studio_auth_signature']??''); $secret=studioConfig('STUDIO_SESSION_SECRET'); if(empty($_SESSION['studio_authenticated'])||$at<1||$secret===''||!hash_equals(hash_hmac('sha256',(string)$at,$secret),$sig))return false; if(time()-$at>STUDIO_SESSION_TTL){$_SESSION=[];session_destroy();return false;} return true; }
function studioActor(): string { if(PHP_SAPI==='cli'&&getenv('VIBE_TEST_MODE')==='1'&&in_array($_SERVER['REMOTE_ADDR']??'', ['127.0.0.1','::1'],true))return 'Local editor'; if(!studioAuthenticated())throw new InvalidArgumentException('Sign in through Studio.',403); return 'Studio editor'; }
function studioLoginPath(): string { return str_starts_with($_SERVER['SCRIPT_NAME']??'','/studio/')?'/studio/login.php':'/login.php'; }
function studioSafeNext(string $next): string { return str_starts_with($next,'/')&&!str_starts_with($next,'//')?$next:'/studio/'; }
function studioRateLimitKey(): string { return hash('sha256',(string)($_SERVER['REMOTE_ADDR']??'unknown')); }
function studioRateLimited(): bool { $p=rtrim(sys_get_temp_dir(),DIRECTORY_SEPARATOR).'/vibe-studio-login-'.studioRateLimitKey().'.json'; $r=is_file($p)?json_decode((string)file_get_contents($p),true):[]; return is_array($r)&&(int)($r['until']??0)>=time(); }
function studioRecordFailure(): void { $p=rtrim(sys_get_temp_dir(),DIRECTORY_SEPARATOR).'/vibe-studio-login-'.studioRateLimitKey().'.json'; $r=is_file($p)?json_decode((string)file_get_contents($p),true):[]; $a=((int)($r['attempts']??0))+1; $d=$a>=5?min(900,30*(2**min(5,$a-5))):0; file_put_contents($p,json_encode(['attempts'=>$a,'until'=>time()+$d]),LOCK_EX); }
function studioLogin(string $password): bool { if(studioRateLimited())return false; $h=studioConfig('STUDIO_PASSWORD_HASH'); $secret=studioConfig('STUDIO_SESSION_SECRET'); $ok=$h!==''&&$secret!==''&&password_verify($password,$h); if(!$ok){studioRecordFailure();return false;} studioStartSession();session_regenerate_id(true);$at=time();$_SESSION['studio_authenticated']=true;$_SESSION['studio_authenticated_at']=$at;$_SESSION['studio_auth_signature']=hash_hmac('sha256',(string)$at,$secret);$_SESSION['studio_csrf']=bin2hex(random_bytes(32));return true; }
function studioLogout(): void { studioStartSession();$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),' ',time()-42000,$p['path'],$p['domain'],(bool)$p['secure'],(bool)$p['httponly']);}session_destroy(); }
function studioRequireAuth(): void { if(PHP_SAPI==='cli'&&getenv('VIBE_TEST_MODE')==='1'){if(in_array($_SERVER['REMOTE_ADDR']??'', ['127.0.0.1','::1'],true)){studioStartSession();return;} http_response_code(403);exit;} if(studioAuthenticated())return; $next=studioSafeNext((string)($_SERVER['REQUEST_URI']??'/studio/')); header('Location: '.studioLoginPath().'?next='.rawurlencode($next),true,303);exit; }
